on:
  push:
  workflow_dispatch:
jobs:
  build:
    name: "Android build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: prisma/prisma-engines
          ref: '2.25.0'
      - name: Use specific Java version for sdkmanager to work
        uses: joschi/setup-jdk@v2
        with:
          java-version: "openjdk8"
          architecture: "x64"
      - name: Delete newer NDK version
        run: |
          rm -rf $ANDROID_HOME/ndk/22*
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
      - run: |
          ls -al ~/
          ls -al ~/.cargo
          echo "[target.armv7-linux-androideabi]" > ~/.cargo/config.toml
          echo "ar = \"${ANDROID_NDK_HOME}/toolchains/llvm/prebuilt/linux-x86_64/bin/arm-linux-androideabi-ar\"" >> ~/.cargo/config.toml
          echo "linker = \"${ANDROID_NDK_HOME}/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi30-clang\"" >> ~/.cargo/config.toml
          cat ~/.cargo/config.toml
      - run: rustup target add armv7-linux-androideabi
      - run: echo "::set-output name=NDK_TOOLCHAINS::${ANDROID_NDK_HOME}/toolchains/llvm/prebuilt/linux-x86_64/bin"
        id: android
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --target armv7-linux-androideabi --release --bin query-engine
        env:
          CC: ${{ steps.android.outputs.NDK_TOOLCHAINS }}/armv7a-linux-androideabi30-clang
          CXX: ${{ steps.android.outputs.NDK_TOOLCHAINS }}/armv7a-linux-androideabi30-clang++
          AR: ${{ steps.android.outputs.NDK_TOOLCHAINS }}/arm-linux-androideabi-ar
          LD: ${{ steps.android.outputs.NDK_TOOLCHAINS }}/arm-linux-androideabi-ld
          RANLIB: ${{ steps.android.outputs.NDK_TOOLCHAINS }}/arm-linux-androideabi-ranlib
          CARGO_PROFILE_RELEASE_LTO: true
          CARGO_PROFILE_RELEASE_OPT_LEVEL: z
          CARGO_PROFILE_RELEASE_CODEGEN_UNITS: 1
      - name: Strip debug symbols
        run: strip target/armv7-linux-androideabi/release/query-engine
      - uses: actions/upload-artifact@v2
        with:
          name: query-engine
          path: target/armv7-linux-androideabi/release/query-engine
